module.exports = {
  onboarding: false,
  requireConfig: "optional",
  vulnerabilityAlerts: { enabled: false },
  ignorePaths: ["template/_components/**"],
  extends: ["helpers:pinGitHubActionDigests", "customManagers:githubActionsVersions"],
  "renovate-config": {
    managerFilePatterns: ["components/delivery/updates/template/renovate.json5"],
  },
  semanticCommits: "enabled",
  prHourlyLimit: 0,
  prConcurrentLimit: 0,
  customEnvVariables: {
    GIT_TERMINAL_PROMPT: "0",
    GIT_CONFIG_COUNT: "1",
    GIT_CONFIG_KEY_0: "url.https://x-access-token:{{ secrets.SOURCE_READ_TOKEN }}@github.com/.insteadOf",
    GIT_CONFIG_VALUE_0: "https://github.com/",
  },
  allowedCommands: [
    "^xargs -a \\.opentofu-version install-tool tofu$",
    "^tofu init -backend=false -input=false -upgrade$",
  ],
  constraints: {
    copier: "9.17.0",
    vendir: "0.46.0",
  },
  customManagers: [
    {
      customType: "regex",
      description: "OpenTofu execution version",
      managerFilePatterns: ["/(^|/)\\.opentofu-version$/", "/(^|/)versions\\.tf$/"],
      matchStrings: [
        "^(?<currentValue>\\d+\\.\\d+\\.\\d+)\\s*$",
        "required_version\\s*=\\s*\"=\\s*(?<currentValue>\\d+\\.\\d+\\.\\d+)\"",
      ],
      depNameTemplate: "opentofu/opentofu",
      datasourceTemplate: "github-releases",
      versioningTemplate: "semver",
      extractVersionTemplate: "^v(?<version>.*)$",
    },
    {
      customType: "regex",
      description: "Copier execution version",
      managerFilePatterns: [
        "/(^|/)\\.github/workflows/.+\\.ya?ml$/",
        "/(^|/)copier\\.yml$/",
        "/(^|/)scripts/accept-template\\.sh$/",
        "/(^|/)components/project/py/(?:base|library)/template/(?:CONTRIBUTING\\.md|scripts/README\\.md)$/",
        "/(^|/)renovate/config\\.js$/",
      ],
      matchStrings: [
        "copier==(?<currentValue>\\d+\\.\\d+\\.\\d+)",
        "_min_copier_version:\\s*\"(?<currentValue>\\d+\\.\\d+\\.\\d+)\"",
        "copier:\\s*\"(?<currentValue>\\d+\\.\\d+\\.\\d+)\"",
      ],
      depNameTemplate: "copier",
      datasourceTemplate: "pypi",
      versioningTemplate: "pep440",
    },
    {
      customType: "regex",
      description: "Vendir execution version",
      managerFilePatterns: ["/(^|/)\\.github/workflows/.+\\.ya?ml$/", "/(^|/)renovate/config\\.js$/"],
      matchStrings: ["vendir:\\s*[\"']?(?<currentValue>\\d+\\.\\d+\\.\\d+)[\"']?"],
      depNameTemplate: "carvel-dev/vendir",
      datasourceTemplate: "github-releases",
      versioningTemplate: "semver",
      extractVersionTemplate: "^v(?<version>.*)$",
    },
    {
      customType: "regex",
      description: "Renovate runtime image",
      managerFilePatterns: ["/(^|/)\\.github/workflows/.+\\.ya?ml$/"],
      matchStrings: [
        "ghcr\\.io/renovatebot/renovate:(?<currentValue>\\d+\\.\\d+\\.\\d+)@(?<currentDigest>sha256:[a-f0-9]{64})",
        "renovate-version:\\s*(?<currentValue>\\d+\\.\\d+\\.\\d+)@(?<currentDigest>sha256:[a-f0-9]{64})",
      ],
      depNameTemplate: "ghcr.io/renovatebot/renovate",
      datasourceTemplate: "docker",
      versioningTemplate: "semver",
    },
    {
      customType: "regex",
      description: "uv required execution version",
      managerFilePatterns: ["/(^|/)components/quality/py/includes/uv/pyproject\\.toml$/"],
      matchStrings: ["required-version\\s*=\\s*\"==(?<currentValue>\\d+\\.\\d+\\.\\d+)\""],
      depNameTemplate: "astral-sh/uv",
      datasourceTemplate: "github-releases",
      versioningTemplate: "semver",
    },
    {
      customType: "regex",
      description: "Local CI runtime tools",
      managerFilePatterns: ["/(^|/)local-ci/versions\\.env$/"],
      matchStrings: [
        "# renovate: datasource=(?<datasource>[^\\s]+) depName=(?<depName>[^\\s]+) versioning=(?<versioning>[^\\s]+) extractVersion=(?<extractVersion>[^\\s]+)\\s+[A-Z0-9_]+_VERSION=(?<currentValue>[^\\s]+)",
      ],
    },
  ],
  packageRules: [
    {
      description: "Component snapshot updates are product fixes",
      matchManagers: ["vendir"],
      semanticCommitType: "fix",
    },
    {
      description: "Use the OpenTofu registry for providers and modules",
      matchDatasources: ["terraform-provider", "terraform-module"],
      registryUrls: ["https://registry.opentofu.org"],
    },
    {
      description: "Regenerate OpenTofu provider locks in the same update",
      matchManagers: ["terraform"],
      matchDepTypes: ["required_provider"],
      postUpgradeTasks: {
        commands: [
          "xargs -a .opentofu-version install-tool tofu",
          "tofu init -backend=false -input=false -upgrade",
        ],
        fileFilters: ["**/.terraform.lock.hcl"],
        workingDirTemplate: "{{{packageFileDir}}}",
      },
    },
    {
      description: "OpenTofu required_version is handled by the explicit OpenTofu manager",
      matchManagers: ["terraform"],
      matchDepTypes: ["required_version"],
      enabled: false,
    },
    {
      description: "Keep Docker dependencies immutable",
      matchDatasources: ["docker"],
      pinDigests: true,
    },
  ],
};
