module.exports = {
  onboarding: false,
  requireConfig: "optional",
  vulnerabilityAlerts: { enabled: false },
  ignorePaths: ["**/_components/**"],
  enabledManagers: ["copier", "custom.jsonata", "github-actions", "pep621", "renovate-config", "vendir"],
  extends: ["helpers:pinGitHubActionDigests"],
  "renovate-config": {
    managerFilePatterns: ["components/delivery/updates/template/renovate.json5"],
  },
  semanticCommits: "enabled",
  prHourlyLimit: 0,
  constraints: {
    copier: "9.17.0",
    vendir: "0.46.0",
  },
  customManagers: [
    {
      customType: "regex",
      description: "OpenTofu execution version",
      managerFilePatterns: ["/(^|/)versions\\.tf$/", "/(^|/)\\.github/workflows/.+\\.ya?ml$/"],
      matchStrings: [
        "required_version\\s*=\\s*\"=\\s*(?<currentValue>\\d+\\.\\d+\\.\\d+)\"",
        "tofu_version:\\s*(?<currentValue>\\d+\\.\\d+\\.\\d+)",
        "\\.\"terraform-version\"\\s*==\\s*\"(?<currentValue>\\d+\\.\\d+\\.\\d+)\"",
      ],
      depNameTemplate: "opentofu/opentofu",
      datasourceTemplate: "github-releases",
      versioningTemplate: "semver",
      extractVersionTemplate: "^v(?<version>.*)$",
    },
    {
      customType: "regex",
      description: "Scalr CLI execution version",
      managerFilePatterns: ["/(^|/)\\.github/workflows/.+\\.ya?ml$/"],
      matchStrings: ["SCALR_CLI_VERSION:\\s*(?<currentValue>\\d+\\.\\d+\\.\\d+)"],
      depNameTemplate: "Scalr/scalr-cli",
      datasourceTemplate: "github-releases",
      versioningTemplate: "semver",
      extractVersionTemplate: "^v(?<version>.*)$",
    },
    {
      customType: "regex",
      description: "actionlint CLI execution version",
      managerFilePatterns: ["/(^|/)\\.github/workflows/.+\\.ya?ml$/"],
      matchStrings: ["github\\.com/rhysd/actionlint/cmd/actionlint@v(?<currentValue>\\d+\\.\\d+\\.\\d+)"],
      depNameTemplate: "rhysd/actionlint",
      datasourceTemplate: "github-releases",
      versioningTemplate: "semver",
      extractVersionTemplate: "^v(?<version>.*)$",
    },
    {
      customType: "regex",
      description: "zizmor CLI execution version",
      managerFilePatterns: ["/(^|/)\\.github/workflows/.+\\.ya?ml$/"],
      matchStrings: ["zizmor==(?<currentValue>\\d+\\.\\d+\\.\\d+)"],
      depNameTemplate: "zizmor",
      datasourceTemplate: "pypi",
      versioningTemplate: "pep440",
    },
    {
      customType: "regex",
      description: "Copier execution version",
      managerFilePatterns: [
        "/(^|/)\\.github/workflows/.+\\.ya?ml$/",
        "/(^|/)copier\\.yml$/",
        "/(^|/)scripts/accept-template\\.sh$/",
        "/(^|/)components/project/py/(?:base|library)/template/(?:CONTRIBUTING\\.md|scripts/README\\.md)$/",
        "/(^|/)renovate/config\\.js$/",
      ],
      matchStrings: [
        "copier==(?<currentValue>\\d+\\.\\d+\\.\\d+)",
        "_min_copier_version:\\s*\"(?<currentValue>\\d+\\.\\d+\\.\\d+)\"",
        "copier:\\s*\"(?<currentValue>\\d+\\.\\d+\\.\\d+)\"",
      ],
      depNameTemplate: "copier",
      datasourceTemplate: "pypi",
      versioningTemplate: "pep440",
    },
    {
      customType: "regex",
      description: "Vendir execution version",
      managerFilePatterns: ["/(^|/)\\.github/workflows/.+\\.ya?ml$/", "/(^|/)renovate/config\\.js$/"],
      matchStrings: ["vendir:\\s*[\"']?(?<currentValue>\\d+\\.\\d+\\.\\d+)[\"']?"],
      depNameTemplate: "carvel-dev/vendir",
      datasourceTemplate: "github-releases",
      versioningTemplate: "semver",
      extractVersionTemplate: "^v(?<version>.*)$",
    },
    {
      customType: "regex",
      description: "Renovate runtime image",
      managerFilePatterns: ["/(^|/)\\.github/workflows/.+\\.ya?ml$/"],
      matchStrings: [
        "ghcr\\.io/renovatebot/renovate:(?<currentValue>\\d+\\.\\d+\\.\\d+)@(?<currentDigest>sha256:[a-f0-9]{64})",
        "renovate-version:\\s*(?<currentValue>\\d+\\.\\d+\\.\\d+)@(?<currentDigest>sha256:[a-f0-9]{64})",
      ],
      depNameTemplate: "ghcr.io/renovatebot/renovate",
      datasourceTemplate: "docker",
      versioningTemplate: "semver",
    },
    {
      customType: "regex",
      description: "OpenTelemetry Collector image",
      managerFilePatterns: ["/(^|/)\\.github/workflows/.+\\.ya?ml$/"],
      matchStrings: [
        "otel/opentelemetry-collector-contrib:(?<currentValue>\\d+\\.\\d+\\.\\d+)@(?<currentDigest>sha256:[a-f0-9]{64})",
      ],
      depNameTemplate: "otel/opentelemetry-collector-contrib",
      datasourceTemplate: "docker",
      versioningTemplate: "semver",
    },
    {
      customType: "regex",
      description: "uv required execution version",
      managerFilePatterns: ["/(^|/)pyproject-uv\\.toml$/"],
      matchStrings: ["required-version\\s*=\\s*\"==(?<currentValue>\\d+\\.\\d+\\.\\d+)\""],
      depNameTemplate: "astral-sh/uv",
      datasourceTemplate: "github-releases",
      versioningTemplate: "semver",
      extractVersionTemplate: "^v(?<version>.*)$",
    },
  ],
  packageRules: [
    {
      description: "Generated product inputs are product fixes",
      matchManagers: ["custom.jsonata", "renovate-config", "vendir"],
      semanticCommitType: "fix",
    },
    {
      description: "Use the OpenTofu registry for providers and modules",
      matchDatasources: ["terraform-provider", "terraform-module"],
      registryUrls: ["https://registry.opentofu.org"],
    },
    {
      description: "OpenTofu required_version is handled by the explicit OpenTofu manager",
      matchManagers: ["terraform"],
      matchDepTypes: ["required_version"],
      enabled: false,
    },
    {
      description: "Keep Docker dependencies immutable",
      matchDatasources: ["docker"],
      pinDigests: true,
    },
    {
      description: "Keep Renovate runtime inputs together",
      matchPackageNames: ["ghcr.io/renovatebot/renovate"],
      groupName: "Renovate runtime",
    },
  ],
};
